import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import AdminLayout from "./AdminLayout";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: {
      children: React.ReactNode;
}) {
      return (
            <html lang="en">
                  <body className={`${inter.className} ${roboto.className} antialiased `}>
                        <ReduxProvider>
                              <AdminLayout>
                                    {children}
                              </AdminLayout>
                        </ReduxProvider>
                  </body>
            </html>
      );
}
